### ISSUE TITLE
Null reference error when trying to add identity

### ISSUE THREAD

**Issue by sebasijan** [leung85/Asp.Net.Identity.SQLite#1]
Hello, I was initially experiencing [this issue](https://stackoverflow.com/questions/47564732/using-the-generic-type-userstore-requires-2-type-arguments?noredirect=1#comment82087909_47564732) which complained 

 > Using the generic type 'UserStore' requires 2 type arguments

So I changed 
    
    var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context.Get<ApplicationDbContext>() as SQLiteDatabase));

to 

    var manager = new ApplicationUserManager(new UserStore<ApplicationUser, IdentityRole>(context.Get<ApplicationDbContext>() as SQLiteDatabase));

Which seems to have worked. However, now when I try adding a new Role to `AspNetRoles` with

    if (!rm.RoleExists(model.UserRole.ToString()))
        rm.Create(new IdentityRole(model.UserRole.ToString()));

I get this error

 > Object reference not set to an instance of an object.

at `RoleStore.cs` line 81:

    TRole result = roleTable.GetRoleByName(roleName) as TRole;

Please can someone help me out with this, not sure what I'm doing wrong this is how I would normally add a new role in asp identity.

Thanks

**Comment by mwkldeveloper** [comment]
@sebasijan   
For 1st Error. You are right,  i forget to update the instruction.
`var manager = new ApplicationUserManager(new UserStore<ApplicationUser, IdentityRole>(context.Get<ApplicationDbContext>() as SQLiteDatabase));`

For second Error, i don't have your source code so i don't know why cannot create a role. 

I add a sample MVC project. You may take a look and git clone the src code.
You can use Postman to test it.   
[Sample](https://github.com/leung85/Asp.Net.Identity.SQLite/tree/master/Sample)

In the sample, You can find RoleController.cs as a reference.

Basically,
You need create a Class ApplicationRoleManager. You can see IdentityConfig.cs

```
public class ApplicationRoleManager : RoleManager<IdentityRole>
	{
		public ApplicationRoleManager(IRoleStore<IdentityRole, string> roleStore)
			: base(roleStore)
		{
		}

		public static ApplicationRoleManager Create(IdentityFactoryOptions<ApplicationRoleManager> options, IOwinContext context)
		{
			var manager = new ApplicationRoleManager(new RoleStore<IdentityRole>(context.Get<ApplicationDbContext>()));
			return manager;
		}
	}
```

And create it in OwinContext (You can find it in Startup.Auth.cs ), so you can use it in RoleController.cs
`app.CreatePerOwinContext<ApplicationRoleManager>(ApplicationRoleManager.Create);`


hope it helps you :)
